### ISSUE TITLE
Add Color Constants

### ISSUE THREAD

**Issue by TravisBumgarner** [TravisBumgarner/strangerer_things#3]

**Comment by tenth10th** [comment]
Going back and looking at the show, the lights are a very odd assortment of colors - Possibly to avoid looking too Christmasy, or to represent Joyce randomly throwing it together(?)

It might actually look better with a more broad selection of random colors, though I suppose we could add color choices ("Show Style", Holiday, Pluralsight Gradient, Random, etc.) to the UI when get get around to that...

That also raises the question of, does each light illuminate in a random color each time it comes on, or do we try to simulate each light having a single color (despite other randomness in their behavior) - Random could look more interesting, but giving each light a static color would allow for pluralsight color gradients, show-accurate light colors, etc...
